* A maven plugin to convert XSD schemas to RNG schemas

This project contains a maven plugin for converting [[https://en.wikipedia.org/wiki/XML_Schema_(W3C)][XSD]] schema files into [[https://en.wikipedia.org/wiki/RELAX_NG][Relax-NG]] schema files.

This plugin looks for all .xsd files in a single directory, and then transforms them into .rng (Relax-NG XML notation) files in a different directory. The .rng files are then converted into .rnc (Relax-NG compact notation) files, that are put in a third directory.

** Status
[[https://github.com/steinarb/xsd-rng-converter-maven-plugin/actions/workflows/xsd-rng-converter-maven-plugin-maven-ci-build.yml][file:https://github.com/steinarb/xsd-rng-converter-maven-plugin/actions/workflows/xsd-rng-converter-maven-plugin-maven-ci-build.yml/badge.svg]]
[[https://coveralls.io/github/steinarb/xsd-rng-converter-maven-plugin][file:https://coveralls.io/repos/github/steinarb/xsd-rng-converter-maven-plugin/badge.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=alert_status#.svg]]
[[https://maven-badges.sml.io/sonatype-central/no.priv.bang.xsd-rng-converter-maven-plugin/xsd-rng-converter-maven-plugin][file:https://maven-badges.sml.io/sonatype-central/no.priv.bang.xsd-rng-converter-maven-plugin/xsd-rng-converter-maven-plugin/badge.svg]]

[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/images/project_badges/sonarcloud-white.svg]]

[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=sqale_index#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=coverage#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=ncloc#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=code_smells#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=sqale_rating#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=security_rating#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=bugs#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=vulnerabilities#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_xsd-rng-converter-maven-plugin&metric=duplicated_lines_density#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_xsd-rng-converter-maven-plugin][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice&metric=reliability_rating#.svg]]

** Using the plugin

Prerequisites
 - Java 21.0.10 or newer
 - Apache maven installed somewhere in PATH

Procedure:
 1. Create a directory to work in
    #+begin_example
      mkdir /tmp/xsdconvert
    #+end_example
 2. Create a minimal pom =/tmp/xsdconvert/pom.xml=
    #+begin_src xml
      <project>
          <modelVersion>4.0.0</modelVersion>

          <groupId>xsdconvert</groupId>
          <artifactId>xsdconvert</artifactId>
          <version>1.0.0-SNAPSHOT</version>

          <build>
              <plugins>
                  <plugin>
                      <groupId>no.priv.bang.maven.plugin</groupId>
                      <artifactId>xsd-rng-converter-maven-plugin</artifactId>
                      <version>1.0.0-SNAPSHOT</version>
                      <executions>
                          <execution>
                              <goals>
                                  <goal>convert</goal>
                              </goals>
                          </execution>
                      </executions>
                  </plugin>
              </plugins>
          </build>
      </project>
    #+end_src
 3. Put the files to be converted in the =src/main/xsd= subdirectory of the directory of the =pom.xml= file
    #+begin_example
      mkdir -p /tmp/xsdconvert/src/main/xsd
      cp *.xsd /tmp/xsdconvert/src/main/xsd/
    #+end_example
 4. Do the conversion
    #+begin_example
      cd /tmp/xsdconvert/
      mvn verify
    #+end_example
 5. The Relax-NG schemas converted from XSD schemas in =/tmp/xsdconvert/src/main/xsd/= can now be found in =/home/xsdconvert/target/classes/rng/=

** About the plugin
This plugin uses what was originally [[https://github.com/kohsuke/msv][Kohsuke Kawaguchi's Multi Schema Validator]] (aka. "The Sun schema converter") to do the conversion from XSD to RNG (Relax-NG XML Notation).

The plugin then uses [[https://relaxng.org/jclark/trang.html][trang]] to convert the RNG files converted from XSD, into [[https://relaxng.org/compact-tutorial-20030326.html][Relax-NG compact notation files]].

I had planned to use the [[http://www.mojohaus.org/exec-maven-plugin/java-mojo.html][exec-maven-plugin exec:java]] goal to run the [[https://github.com/kohsuke/msv/blob/master/rngconverter/src/main/java/com/sun/msv/writer/relaxng/Driver.java#L31][RNGCOnverter main]], but that would only let me convert a single XSD file per maven project (or per POM execution configuration).  And using the [[http://maven.apache.org/plugins/maven-antrun-plugin/][maven-antrun-plugin]] seemed like it would be as much work as simply writing a mojo.

So writing a new mojo is what I did.

** Release history
** License

The xsd-rng-converter-maven-plugin is licensed under the Apache license v. 2.

See the LICENSE file for details.
